Removed requirement for  column from experiments endpoint
PecanProject/BETYdb-YABA pull request #35
Opened 2020-03-03 20:54 UTC by im-prakher

Fixed #32

2020-03-04 11:11 UTC, rahul799 requested changes

2020-03-04 11:11 UTC, rahul799 commented on app/yaba.yaml
>                      'MAC Season 8: Border','2019-01-01','2019-03-31','ProMix BRK20 14-14-14 Osmocote pots; pre-filled by Hummert Sorghum seed Conviron Growth House'....,'Grain Sorghum also planted to
```suggestion
                    'MAC Season 8: Border','2019-01-01','2019-03-31','ProMix BRK20 14-14-14 Osmocote pots; pre-filled by Hummert Sorghum seed Conviron Growth House'
```
I guess this must be removed too.

2020-03-04 17:52 UTC, Chris-Schnaufer approved these changes

2020-03-05 17:57 UTC, KristinaRiemer commented
I'm getting this error when I run the curl statement for the experiments endpoint: 

```
{
  "Message": "(psycopg2.errors.UniqueViolation) duplicate key value violates unique constraint \"unique_name_per_species\""
}
```
Some more info about the error: 
```
yaba_api_1     | psycopg2.errors.NotNullViolation: null value in column "description" violates not-null constraint
yaba_api_1     | DETAIL:  Failing row contains (99000000025, MAC Season 8: Border , 2019-01-01, 2019-03-31, null, , 99000000036, 2020-03-05 17:50:18.732026, 2020-03-05 17:50:18.732026).
```

2020-03-06 05:32 UTC, rahul799 requested changes

2020-03-06 05:32 UTC, rahul799 commented on input_files/experiments.csv
> -MAC Season 8: DP test,2019-01-01,2019-03-31,some text,
The error is happening due to the deletion in these lines. The description row contains the value wefu, some text, etc.

2020-03-25 11:38 UTC, im-prakher commented
Sorry for catching up so late, got involved in some health issues but now I am fine. I think this will work now

2020-05-06 21:57 UTC, dlebauer commented
@im-prakher could you please confirm that this makes the design column optional rather than removing it?

2020-05-07 15:24 UTC, im-prakher commented
Yeah! I will look into this

On Thu 7 May, 2020, 3:27 AM David LeBauer, <notifications@github.com> wrote:

> @im-prakher <https://github.com/im-prakher> could you please confirm that
> this makes the design column optional rather than removing it?
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/PecanProject/BETYdb-YABA/pull/35#issuecomment-624912380>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AKJGR5VQKQOTWJBLMHK2YC3RQHMLVANCNFSM4LAS2WWQ>
> .
>

2020-05-08 12:00 UTC, im-prakher commented
I have finally removed the requirement for the design column, earlier there was an issue with CSV format of experiments.csv now I have fixed it.

2020-06-22 22:13 UTC, merged